#spring.application.name=CartService
#
#eureka.client.service-url.defaultZone=http://localhost:8082/eureka/

server:
  port: 8081
spring:
  application:
    name: CartService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/