#server.port= 8085
#spring.application.name=ProductCatalogService
#eureka.client.service-url.defaultZone=http://localhost:8082/eureka/

#server.port=8081
#spring.application.name=OrderService
#eureka.client.service-url.defaultZone=http://localhost:8082/eureka/

server:
  port: 8084
spring:
  application:
    name: ProductCatalogService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/